<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuotesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('quotes')->insert([
            [
                'id' => 399,
                'language' => 'ru',
                'quote' => 'В сегодняшнем понимании риск — это в первую очередь бездействие.',
                'meaning' => '• Роберт Кийосаки',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 400,
                'language' => 'ru',
                'quote' => 'Cамая трудная для понимания вещь на свете — это подоходный налог.',
                'meaning' => '• Альберт Эйнштейн',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 401,
                'language' => 'ru',
                'quote' => 'Истинное величие начинается с понимания собственного ничтожества.',
                'meaning' => '• Иоганн Вольфганг Гёте',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 402,
                'language' => 'ru',
                'quote' => 'Мир невозможно удержать силой. Его можно лишь достичь пониманием.',
                'meaning' => '• Альберт Эйнштейн',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 403,
                'language' => 'ru',
                'quote' => 'Разум — это понимание сущности вещей.',
                'meaning' => '• Мо-цзы',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 404,
                'language' => 'ru',
                'quote' => 'Бесполезны те знания, что лишены понимания.',
                'meaning' => '• Dubrovka Oleg',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 405,
                'language' => 'ru',
                'quote' => 'Вера предшествует пониманию.',
                'meaning' => '• Аврелий Августин',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 406,
                'language' => 'ru',
                'quote' => 'Работайте, работайте — а понимание придёт потом.',
                'meaning' => '• Жан Лерон Д’Аламбер',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 407,
                'language' => 'ru',
                'quote' => 'Понимание себя — начало мудрости.',
                'meaning' => '• Джидду Кришнамурти',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 408,
                'language' => 'ru',
                'quote' => 'Понимание — начало согласия.',
                'meaning' => '• Бенедикт Спиноза',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 409,
                'language' => 'ru',
                'quote' => 'Как много мы знаем, и как мало мы понимаем.',
                'meaning' => '• Альберт Эйнштейн',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 410,
                'language' => 'ru',
                'quote' => 'Всё, что раздражает в других, может вести к пониманию себя.',
                'meaning' => '• Карл Густав Юнг',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 411,
                'language' => 'ru',
                'quote' => 'Я ем, чтобы жить, а другие люди живут, чтобы есть.',
                'meaning' => '• Сократ',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 412,
                'language' => 'ru',
                'quote' => 'Вершина удовольствия - это радость понимания.',
                'meaning' => '• Леонардо да Винчи',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 413,
                'language' => 'ru',
                'quote' => 'Серые умы обычно осуждают то, что выходит за рамки их понимания.',
                'meaning' => '• Франсуа де Ларошфуко',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 414,
                'language' => 'ru',
                'quote' => 'Мир не может быть достигнут через насилие, он может быть обретен только через взаимопонимание.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 415,
                'language' => 'ru',
                'quote' => 'Каждую минуту гнева ты теряешь 60 секунд счастья.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 416,
                'language' => 'ru',
                'quote' => 'Мир уступает дорогу тому, кто знает, куда идет.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 417,
                'language' => 'ru',
                'quote' => 'Вы так громко кричите мне в уши, что я не слышу; что вы говорите.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 418,
                'language' => 'ru',
                'quote' => 'Всегда делай то, что ты боишься сделать.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 419,
                'language' => 'ru',
                'quote' => 'Земля смеется цветами.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 420,
                'language' => 'ru',
                'quote' => 'Герой не храбрее обычного человека, он просто храбрый на пять минут больше.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 421,
                'language' => 'ru',
                'quote' => 'Великий человек всегда хочет быть маленьким.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 422,
                'language' => 'ru',
                'quote' => 'Мелкие люди верят в удачу.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 423,
                'language' => 'ru',
                'quote' => 'Соорудите мышеловку получше, и у вашей двери будет толпиться весь мир.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 424,
                'language' => 'ru',
                'quote' => 'Люди, кажется, не понимают, что их мировоззрение отображает их личность.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 425,
                'language' => 'ru',
                'quote' => 'Настоящие победы — это победы мира, а не войны.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 426,
                'language' => 'ru',
                'quote' => 'Чем меньше человек думает или знает о своих достоинствах, тем больше он нравится нам.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 427,
                'language' => 'ru',
                'quote' => 'Когда глаза говорят одно, а язык другое, опытный человек больше верит первым.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 428,
                'language' => 'ru',
                'quote' => 'То, чему мы учились в школах и университетах, не образование, а только способ получить образование.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 429,
                'language' => 'ru',
                'quote' => 'Мы становимся тем, о чем думаем целыми днями.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 430,
                'language' => 'ru',
                'quote' => 'Людей следует принимать небольшими дозами.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 431,
                'language' => 'ru',
                'quote' => 'Воображение — это не талант некоторых, но здоровье каждого.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 432,
                'language' => 'ru',
                'quote' => 'Любовь к красоте — это вкус. Создание красоты — это искусство.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 433,
                'language' => 'ru',
                'quote' => 'Единственный способ иметь друга — самому быть им.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 434,
                'language' => 'ru',
                'quote' => 'Человек сделан из книг, которые он читает.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 435,
                'language' => 'ru',
                'quote' => 'За деньги можно купить почти все — кроме теплоты человеческого сердца.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 436,
                'language' => 'ru',
                'quote' => 'Никто еще не достиг величия, следуя школьным правилам.',
                'meaning' => '• Ральф Уолдо Эмерсон',
                'image_path' => 'images/logo.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            
        ]);
    }
}
